server:
  port: 8080

spring:
  application:
    name: store

  config:
    import: classpath:application-db.yml

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mariadb://${local-db.host}:${local-db.port}/${local-db.name}?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: ${local-db.username}
    password: ${local-db.password}

  jpa:
    properties:
      hibernate:
        format_sql: true            # SQL ?? ?? ??
        highlight_sql: true         # SQL ??
        hbm2ddl.auto: create-drop

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health
    jmx:
      exposure:
        exclude: '*'
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

