# local(개발 환경), dev(도커 환경)
# ex))))) java -jar test-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod

# 기본값은 local 프로필으로 설정
spring:
  profiles:
    default: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/exception
    fallback-to-system-locale: false

---
spring:
  config:
    activate:
      on-profile: local, dev