server:
  port: 8080

spring:
  config:
    import: classpath:application-db.yml

  datasource:
    url: jdbc:mariadb://${local-db.host}:${local-db.port}/${local-db.name}?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: ${local-db.username}
    password: ${local-db.password}

  jpa:
    properties:
      hibernate:
        format_sql: true            # SQL 보기 좋게 출력
        highlight_sql: true         # SQL 색깔
        hbm2ddl.auto: create-drop

  flask:
    base-url: ${local-db.flaskUrl}

project:
  imagePath: "image/"